server:
  port: 8022


  spring:
   datasource:
    url: jdbc:mysql://192.168.10.11:3306/greenlife?characterEncoding=UTF-8&useSSL=true
    username: root
    password:  zjly@2015
    driver-class-name: com.mysql.jdbc.Driver